import Head from "next/head";
import Navbar from "../components/navbar/Navbar";
import EmployeeTable from "../components/employeeTable/EmployeeTable";
import Button from "@material-ui/core/Button";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Resume Keeper</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />
      <div style={{ padding: "30px" }}>
        <EmployeeTable />
      </div>
      <div style={{ display: "flex", justifyContent: "center" }}>
        <Button variant="contained" color="secondary">
          Previous
        </Button>
        <Button
          style={{ marginLeft: "5px" }}
          variant="contained"
          color="secondary"
        >
          Next
        </Button>
      </div>
      <footer style={{ display: "flex", justifyContent: "center" }}>
        <p style={{ position: "absolute", bottom: 0 }}>
          © 2006-2021 Monstarlab
        </p>
      </footer>
    </div>
  );
}
