import Head from "next/head";
import Navbar from "../components/navbar/Navbar";
import EmployeeTable from "../components/employeeTable/EmployeeTable";
import { Button, Typography } from "@material-ui/core";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Resume Keeper</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <Typography
        color="primary"
        variant="h4"
        style={{ textAlign: "center", fontWeight: "500", marginTop: "2rem" }}
      >
        Employee List
      </Typography>
      <div style={{ padding: "30px", maxWidth: "70%", margin: "auto" }}>
        <EmployeeTable />
      </div>
      <div style={{ display: "flex", justifyContent: "center" }}>
        <Button variant="contained" color="secondary">
          Previous
        </Button>
        <Button
          style={{ marginLeft: "5px" }}
          variant="contained"
          color="secondary"
        >
          Next
        </Button>
      </div>
      <footer style={{ display: "flex", justifyContent: "center" }}>
        <p style={{ position: "absolute", bottom: 0 }}>
          © 2006-2021 Monstarlab
        </p>
      </footer>
    </div>
  );
}
